[package]
name = 'sc_users'
version = '1.0.0'
upgrade_policy = "arbitrary"

[addresses]
sc = "_"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = 'aptos-move/framework/aptos-framework' }
Users = { local = "../interface_users" }


